name: CI Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pipeline_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Job Message
        run: echo "Job pipeline_workflow is executing as part of new workflow"
      
      - name: Trigger Jenkins Job
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JOB_NAME: 'GitHub-Integration'
        run: |
          echo "Triggering Jenkins job: $JOB_NAME"
          curl -X POST "$JENKINS_URL/job/$JOB_NAME/build" \
            --user $JENKINS_USER:$JENKINS_TOKEN \
            || { echo "Jenkins trigger failed"; exit 1; }
